config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "notes#index"
  get "/users/collections", to: "users/collections#index"
  get "/users/profiles/:id", to: "users/profiles#public_note", as: 'user_public_note'
  get "/users/profiles/:id/liked", to: "users/profiles#like_note", as: 'user_like_note_liked'
  get "/users/profiles/:id/private", to: "users/profiles#private_note", as: 'user_private_note_private'
  
  
  resources :notes do
    member do
      get :is_public
    end
    resources :comments, shallow: true, only: [:create, :destroy]
  end
  
  namespace :api do
    namespace :v1 do
      resources :notes, only: [] do
        member do
          post :collection
          post :favorite
          post :tag
        end
        collection do
          post :tag_filter
        end
      end
      resources :comments, only: [] do
        member do
          post :edit_comment
        end
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable, omniauth_providers: [:github, :google_oauth2, :facebook]

  has_one_attached :avatar

  has_many :notes, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_many :collected_notes, through: :collections, source: :note, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorite_notes, through: :likes, source: :note, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy


  def favorite?(n)
    favorite_notes.exists?(n.id)
  end

  def collect?(n)
    collected_notes.exists?(n.id)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!

    end
  end
end

app/controllers/users/collections_controller.rb
class Users::CollectionsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @collections = current_user.collected_notes.order(updated_at: params[:desc] || :desc).search(params[:search]).page(params[:page])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
      else
        session["devise.github_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to notes_path
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def public_note
    @notes = @user.notes.order(updated_at: params[:desc] || :desc)
                        .where(public_status: true)
                        .search(params[:search])
                        .page(params[:page])  
  end  

  def private_note
    @notes = @user.notes.order(updated_at: params[:desc] || :desc)
                        .search(params[:search])
                        .page(params[:page])  
  end
  
  def like_note
    @notes = @user.favorite_notes.order(updated_at: params[:desc] || :desc)
                                 .search(params[:search])
                                 .page(params[:page])
  end

  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create , :update]
  # before_action :configure_account_update_params, only: [:update]
  def user_params
    accessible = [
      :name,
      :email,
      :password,
      :password_confirmation,
      :intro,
      :avatar
    ]
    params.require(:user).permit(accessible)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
  # current_user holds the logged in user
  @user = current_user
  # IF they've left the password field blank, 
  # AND the devise update_without_password method returns true
  # OR IF a full update of user (including password and password_confirmation) returns true
  # THEN re-sign them in to flush their session, and redirect them back to their dashboard, and send a success message.
  # ELSE re-present the edit form they were just on (there's a handy catcher
  # in the edit view script to render the form errors, you can find them on
  # @user.errors)

  if (user_params[:password].blank? && @user.update_without_password(user_params)) || @user.update(user_params)
    sign_in(@user, bypass: true)
    redirect_to '/users/edit', notice: 'Your profile changes have been saved.'
  else
    render 'edit'
  end
end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :intro])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :intro])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_in
  def new
    super
  end



  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/profiles/like_note.html.erb
<section class="bg-gray-rackmd text-white flex">
  <div class="w-80 bg-gray-dark px-3 py-5 text-xl h-screen sticky top-0">
    <div>
      <i class="fas fa-book-open text-xl"></i><%= link_to "RackMD", notes_path,class:"text-left no-underline text-white" %></i>
    </div>
    <div class="flex justify-center items-center pt-4">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar.url, size: '100x100', class: 'rounded-full' %>
      <% else %>
        <%= image_tag("104.png",:size => "100x100") %>
      <% end %>
    </div>
    <div class="px-3 my-5">
      <div class="text-center text-2xl my-4"><%= @user.name %></div>
      <div class="my-4 text-center">
        <%= link_to '修改個人資料', edit_registration_path(:user),class:"no-underline text-white text-lg py-2 px-8 rounded bg-blue-500 hover:bg-blue-700 "%>
      </div>
      <div class="text-xs py-3 ml-6 text-gray-400">
        從 <%=@user.created_at.strftime("%Y年%m月%d日") %> 開始加入 RackMD 
      </div>
    </div>
  </div>
  <main class="profile w-full h-full p-5">
    <div class="text-sm text-gray-400">
      <%= link_to user_private_note_private_path(current_user) do%>
        <i class="fas fa-lock w-36 text-lg hover:text-white"> 我擁有的筆記</i>
      <% end %>
      <%= link_to "公開筆記", user_public_note_path(current_user), class:"ml-2 hover:text-white text-lg" %>
      <%= link_to "讚賞列表", user_like_note_liked_path(current_user), class:"ml-3 hover:text-white text-lg" %>
    </div>
    <div class="hr border-0 bg-gray-300 h-px mt-2 mb-8"> 
    </div>
    <div class="flex justify-between items-center mb-5">
      <div class="border border-gray-200 rounded w-56 p-1">
        <%= form_tag(user_like_note_liked_path, :method => "get", class:"my-0.5") do %>
          <i class="fas fa-search text-gray-200 text-base"></i>
          <%= text_field_tag :search, nil, placeholder: "搜尋筆記...", class:"bg-gray-rackmd focus:outline-none text-gray-200" %>
          <%= submit_tag "搜尋" ,:note_name => nil, class: "hidden" %>
        <% end %>
      </div>
      <button class="w-8 border border-gray-200 bg-gray-rackmd text-white relative"
              data-controller="commentToggle" 
              data-action="commentToggle#toggle">
        <div>
          <i class="fas fa-chevron-down h-5 w-full flex items-center justify-center text-gray-200 hover:bg-gray-200 hover:text-gray-700"></i>
        </div>
        <div class="absolute top-full right-0 mt-0.5 py-2 w-40 bg-gray-light rounded"
              style="display: none;"
              data-commentToggle-target="display">
          <div class="text-gray-300 text-base text-left px-4">
            筆記排序
          </div>
          <div class="text-sm">
            <%= link_to "新到舊",
                        user_like_note_liked_path(desc: 'desc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
            <%= link_to "舊到新", 
                        user_like_note_liked_path(desc: 'asc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
          </div>
        </div>
      </button>
    </div>
    <% @notes.each do |note| %>
      <div class="w-full bg-gray-dark my-0.5 px-8 py-5">
        <h2 class= "text-gray-200 text-xl">
          <%= link_to note.title, note_path(note) %>
        </h2>
        <p class= "text-gray-400 text-base">
          <%= truncate note.content.remove(note.title,",","•","#"), length: 50 %>
        </p>
        <div class="flex text-gray-400 text-sm">
          <div>
            <%= note.user.name %> 變更 <%= day_difference(note) %>
          </div>
          <div class="ml-2">
            <i class="fas fa-eye w-16">閱讀模式</i>
          </div>
          <div data-controller="favorite" 
              data-favorite-id-value="<%= note.id %>">
            <a href="#"
              id = "favorite_btn"
              data-action="favorite#addFavorite"
              data-id="<%= note.id %>">
              <%= favorite_icon(current_user, note) %>讚賞 
            </a>
            <span data-favorite-target='counter' >
              <%= @likes %>
            </span>
          </div>
          <div data-controller="collect" 
              data-collect-id-value="<%= note.id %>">
            <a data-action="collect#addCollection">
              <%= collection_icon(current_user, note) %>收藏
            </a>
          </div>
        </div>
      </div>
    <% end %>
    <div class=" flex justify-center mt-5 ml-auto">
      <%= paginate @notes %>
    </div>
  </main>
</section>

app/views/users/profiles/private_note.html.erb
<section class="bg-gray-rackmd text-white flex">
  <div class="w-80 bg-gray-dark px-3 py-5 text-xl h-screen sticky top-0">
    <div>
      <i class="fas fa-book-open text-xl"></i><%= link_to "RackMD", notes_path,class:"text-left no-underline text-white" %></i>
    </div>
    <div class="flex justify-center items-center pt-4">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar.url, size: '100x100', class: 'rounded-full' %>
      <% else %>
        <%= image_tag("104.png",:size => "100x100") %>
      <% end %>
    </div>
    <div class="px-3 my-5">
      <div class="text-center text-2xl my-4"><%= @user.name %></div>
      <div class="my-4 text-center">
        <%= link_to '修改個人資料', edit_registration_path(:user),class:"no-underline text-white text-lg py-2 px-8 rounded bg-blue-500 hover:bg-blue-700 "%>
      </div>
      <div class="text-xs py-3 ml-6 text-gray-400">
        從 <%=@user.created_at.strftime("%Y年%m月%d日") %> 開始加入 RackMD 
      </div>
    </div>
  </div>
  <main class="profile w-full h-full p-5">
    <div class="text-sm text-gray-400">
      <%= link_to user_private_note_private_path(current_user) do%>
        <i class="fas fa-lock w-36 text-lg hover:text-white"> 我擁有的筆記</i>
      <% end %>
      <%= link_to "公開筆記", user_public_note_path(current_user), class:"ml-2 hover:text-white text-lg" %>
      <%= link_to "讚賞列表", user_like_note_liked_path(current_user), class:"ml-3 hover:text-white text-lg" %>
    </div>
    <div class="hr border-0 bg-gray-300 h-px mt-2 mb-8"> 
    </div>
    <div class="flex justify-between items-center mb-5">
      <div class="border border-gray-200 rounded w-56 p-1">
        <%= form_tag(user_private_note_private_path, :method => "get", class:"my-0.5") do %>
          <i class="fas fa-search text-gray-200 text-base"></i>
          <%= text_field_tag :search, nil, placeholder: "搜尋筆記...", class:"bg-gray-rackmd focus:outline-none text-gray-200" %>
          <%= submit_tag "搜尋" ,:note_name => nil, class: "hidden" %>
        <% end %>
      </div>
      <button class="w-8 border border-gray-200 bg-gray-rackmd text-white relative"
              data-controller="commentToggle" 
              data-action="commentToggle#toggle">
        <div>
          <i class="fas fa-chevron-down w-full h-5 flex items-center justify-center text-gray-200 hover:bg-gray-200 hover:text-gray-700"></i>
        </div>
        <div class="absolute top-full right-0 mt-0.5 py-2 w-40 bg-gray-light rounded"
              style="display: none;"
              data-commentToggle-target="display">
          <div class="text-gray-300 text-base text-left px-4">
            筆記排序
          </div>
          <div class="text-sm">
            <%= link_to "新到舊",
                        user_private_note_private_path(desc: 'desc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
            <%= link_to "舊到新", 
                        user_private_note_private_path(desc: 'asc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
          </div>
        </div>
      </button>
    </div>
    <% @notes.each do |note| %>
      <div class="w-full bg-gray-dark my-0.5 px-8 py-5">
        <h2 class= "text-gray-200 text-xl">
          <%= link_to note.title, note_path(note) %>
        </h2>
        <p class= "text-gray-400 text-base">
          <%= truncate note.content.remove(note.title,",","•","#"), length: 50 %>
        </p>
        <div class="flex text-gray-400 text-sm">
          <div>
            <%= note.user.name %> 變更 <%= day_difference(note) %>
          </div>
          <div class="ml-2">
            <i class="fas fa-eye w-16">閱讀模式</i>
          </div>
          <div data-controller="favorite" 
              data-favorite-id-value="<%= note.id %>">
            <a href="#"
              id = "favorite_btn"
              data-action="favorite#addFavorite"
              data-id="<%= note.id %>">
              <%= favorite_icon(current_user, note) %>讚賞 
            </a>
            <span data-favorite-target='counter' >
              <%= @likes %>
            </span>
          </div>
          <div data-controller="collect" 
              data-collect-id-value="<%= note.id %>">
            <a data-action="collect#addCollection">
              <%= collection_icon(current_user, note) %>收藏
            </a>
          </div>
        </div>
      </div>
    <% end %>
    <div class=" flex justify-center mt-5 ml-auto">
      <%= paginate @notes %>
    </div>
  </main>
</section>

app/views/users/profiles/public_note.html.erb
<section class="bg-gray-rackmd text-white flex">
  <div class="w-80 bg-gray-dark px-3 py-5 text-xl h-screen sticky top-0">
    <div>
      <i class="fas fa-book-open text-xl"></i><%= link_to "RackMD", notes_path,class:"text-left no-underline text-white" %></i>
    </div>
    <div class="flex justify-center items-center pt-4">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar.url, size: '100x100', class: 'rounded-full' %>
      <% else %>
        <%= image_tag("104.png",:size => "100x100") %>
      <% end %>
    </div>
    <div class="px-3 my-5">
      <div class="text-center text-2xl my-4"><%= @user.name %></div>
      <div class="my-4 text-center">
        <%= link_to '修改個人資料', edit_registration_path(:user),class:"no-underline text-white text-lg py-2 px-8 rounded bg-blue-500 hover:bg-blue-700 "%>
      </div>
      <div class="text-xs py-3 ml-6 text-gray-400">
        從 <%=@user.created_at.strftime("%Y年%m月%d日") %> 開始加入 RackMD 
      </div>
    </div>
  </div>
  <main class="profile w-full h-full p-5">
    <div class="text-sm text-gray-400">
      <%= link_to user_private_note_private_path(current_user) do%>
        <i class="fas fa-lock w-36 text-lg hover:text-white"> 我擁有的筆記</i>
      <% end %>
      <%= link_to "公開筆記", user_public_note_path(current_user), class:"ml-2 hover:text-white text-lg" %>
      <%= link_to "讚賞列表", user_like_note_liked_path(current_user), class:"ml-3 hover:text-white text-lg" %>
    </div>
    <div class="hr border-0 bg-gray-300 h-px mt-2 mb-8"> 
    </div>
    <div class="flex justify-between items-center mb-5">
      <div class="border border-gray-200 rounded w-56 p-1">
        <%= form_tag(user_public_note_path, :method => "get", class:"my-0.5") do %>
          <i class="fas fa-search text-gray-200 text-base"></i>
          <%= text_field_tag :search, nil, placeholder: "搜尋筆記...", class:"bg-gray-rackmd focus:outline-none text-gray-200" %>
          <%= submit_tag "搜尋" ,:note_name => nil, class: "hidden" %>
        <% end %>
      </div>
      <button class="w-8 border border-gray-200 bg-gray-rackmd text-white relative"
              data-controller="commentToggle" 
              data-action="commentToggle#toggle">
        <div>
          <i class="fas fa-chevron-down w-full h-5 flex items-center justify-center text-gray-200 hover:bg-gray-200 hover:text-gray-700"></i>
        </div>
        <div class="absolute top-full right-0 mt-0.5 py-2 w-40 bg-gray-light rounded"
              style="display: none;"
              data-commentToggle-target="display">
          <div class="text-gray-300 text-base text-left px-4">
            筆記排序
          </div>
          <div class="text-sm">
            <%= link_to "新到舊",
                        user_public_note_path(desc: 'desc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
            <%= link_to "舊到新", 
                        user_public_note_path(desc: 'asc'),
                        class:"block text-left py-0.5 px-4 text-gray-200 hover:bg-gray-400" %>
          </div>
        </div>
      </button>
    </div>
    <% @notes.each do |note| %>
      <div class="w-full bg-gray-dark my-0.5 px-8 py-5">
        <h2 class= "text-gray-200 text-xl">
          <%= link_to note.title, note_path(note) %>
        </h2>
        <p class= "text-gray-400 text-base">
          <%= truncate note.content.remove(note.title,",","•","#"), length: 50 %>
        </p>
        <div class="flex text-gray-400 text-sm">
          <div>
            <%= note.user.name %> 變更 <%= day_difference(note) %>
          </div>
          <div class="ml-2">
            <i class="fas fa-eye w-16">閱讀模式</i>
          </div>
          <div data-controller="favorite" 
              data-favorite-id-value="<%= note.id %>">
            <a href="#"
              id = "favorite_btn"
              data-action="favorite#addFavorite"
              data-id="<%= note.id %>">
              <%= favorite_icon(current_user, note) %>讚賞 
            </a>
            <span data-favorite-target='counter' >
              <%= @likes %>
            </span>
          </div>
          <div data-controller="collect" 
              data-collect-id-value="<%= note.id %>">
            <a data-action="collect#addCollection">
              <%= collection_icon(current_user, note) %>收藏
            </a>
          </div>
        </div>
      </div>
    <% end %>
    <div class=" flex justify-center mt-5 ml-auto">
      <%= paginate @notes %>
    </div>
  </main>
</section>