config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "notes#index"
  get "/users/collections", to: "users/collections#index"
  get "/users/profiles/:id", to: "users/profiles#public_note", as: 'user_public_note'
  get "/users/profiles/:id/liked", to: "users/profiles#like_note", as: 'user_like_note_liked'
  get "/users/profiles/:id/private", to: "users/profiles#private_note", as: 'user_private_note_private'
  
  
  resources :notes do
    member do
      get :is_public
    end
    resources :comments, shallow: true, only: [:create, :destroy]
  end
  
  namespace :api do
    namespace :v1 do
      resources :notes, only: [] do
        member do
          post :collection
          post :favorite
          post :tag
        end
        collection do
          post :tag_filter
        end
      end
      resources :comments, only: [] do
        member do
          post :edit_comment
        end
      end
    end
  end

end

app/models/note.rb
class Note < ApplicationRecord
  paginates_per 8
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorite_notes, through: :likes, source: :user, dependent: :destroy
  has_many :collections, dependent: :destroy



  def save_tag(tag_list, note)
    self.tags = tag_list.map do |tag|
      Tag.where(title: tag, user_id: note.user_id).first_or_create!
    end 
  end

  def self.search(search) 
    if search
      where(['title LIKE ?', "%#{search}%"]) 
    else
      all 
    end	
  end 

  def find_like(user)
    self.likes.where( :user => user.id ).first
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < ApplicationController
  before_action :authenticate_user!

  def collection
    note = Note.find(params[:id])

    if Collection.exists?(note: note)
      current_user.collected_notes.delete(note)
      render json: { status: 'removed' }
    else
      current_user.collected_notes << note
      render json: { status: 'added' }
    end
  end

  def favorite
    note = Note.find(params[:id])
    if Like.exists?(note: note)
      current_user.favorite_notes.delete(note)
      render json: { status: 'removed', id: params[:id] }
    else
      current_user.favorite_notes << note
      render json: { status: 'added', id: params[:id] }
    end
  end

  def tag
    tag_list = params[:tag_str].split(',')
    @note = Note.find(params[:id])
    @note.save_tag(tag_list, @note)
    render json: { status: 'tags saved' }
  end

  def tag_filter
    @notes = current_user.notes
    @taggings = Tagging.all
    render json: { note: @notes, tagging: @taggings}
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_note, only: [:edit, :update, :destroy]
  def index
    if current_user.notes.exists?
      @notes = current_user.notes.order(updated_at: params[:desc] || :desc).search(params[:search]).page(params[:page])
      @tags = current_user.tags.search(params[:search])
    else
      render "firstuse"
    end
  end

  def show
    @note = Note.find(params[:id])
    if !@note.public_status && @note.user != current_user
      redirect_to "/"
    else
      @comment = @note.comments.new
      @comments = @note.comments.order(updated_at: :asc)
      @likes = @note.likes.count
    end
  end

  def create
    @note = current_user.notes.create!
    redirect_to "/notes/#{@note.id}"
  end

  def edit
  end

  def update
    if @note.update(note_params)
      render json: @note.title
    else
      render json: {status: "error", message: "Save error"}
    end
  end

  def destroy
    if @note.destroy
      redirect_to "/notes"
    end
  end

  def is_public
    @note = Note.find(params[:id])
    if @note.public_status
      @note.update(public_status: false)
    else
      @note.update(public_status: true)
    end
    redirect_to note_path(@note)
  end
  
  private 
  def note_params
    params.require(:note).permit(:title, :content, :tag_list)
  end

  def find_user_note
    @note = current_user.notes.find(params[:id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def favorite_icon(user, note)
    if user && user.favorite?(note)
      shape = 'fas'
    else
      shape = 'far'
    end
    content_tag(:i, '', class: ['fa-heart', 'favorite_icon', 'text-sm', shape], data: { 'favorite-target': 'icon'})
  end

  def collection_icon(user, note)
    if user && user.collect?(note)
      shape = 'fas'
    else
      shape = 'far'
    end
    content_tag(:i, '', class: ['fa-bookmark', 'collection_icon', 'text-sm', 'cursor-pointer', shape], data: { 'collect-target': 'icon'})
  end

  def day_difference(note)
    (time_ago_in_words(note.updated_at))
  end

  def publicbtn_display(note)
    if note.public_status && note.user != current_user
    else
      if note.public_status
        link_to is_public_note_path(note),
                class: 'h-8 w-48 border border-blue-600 flex justify-center items-center hover:border-gray-400 group rounded' do
          # content_tag 如要包多個 content_tag 需加 concat，來源：https://gist.github.com/abhilashak/a67eab371c54e1e71e1002f9c2dd791d?fbclid=IwAR1WNpsAtp8bR_AdrRjQycbzgK9PXegBOSdqCsQXPrrq7oo-W1ZNI0GH5vw
          content_tag(:div, '', class: ['flex w-24 relative']) do
            concat(content_tag(:i, '', class: ['fas fa-globe-asia text-sm text-blue-600  flex justify-center items-center group-hover:opacity-0']))
            concat(content_tag(:span, '已公開發表', class: ['w-24 text-sm text-blue-600  group-hover:opacity-0']))
            concat(content_tag(:span, '取消公開發表', class: ['w-24 text-sm text-gray-400 opacity-0 group-hover:opacity-100 absolute']))
          end
        end
      else
        link_to is_public_note_path(note),
                class: 'h-8 w-48 border border-blue-600 flex justify-center items-center bg-blue-600 hover:bg-blue-700 relative rounded' do
          content_tag(:div, '我要公開發表', class: ['w-24 text-sm text-white absolute'])
        end
      end
    end
  end

  def commentbtn_display(comment)
    if comment.user_id == current_user.id
      content_tag(:i, '', class: ['fas fa-ellipsis-v'])
    else
    end
  end
end

app/views/notes/_comment.html.erb
<div class="relative">
  <div id="comment_<%= comment.id %>"
       data-controller="editComment commentToggle"
       data-editComment-id-value="<%= comment.id %>"
       class="px-3.5 border-b border-gray-300 mb-2">
    <div class="flex">
      <div class="flex justify-center items-start mr-1 mt-1">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar.url, size: '20x20', class: 'rounded-full' %>
        <% else %>
          <%= image_tag("104.png",:size => "20x20") %>
        <% end %>
      </div>
      <div>
        <div class="flex justify-between">
          <div class="text-xl">
            <%= comment.user.name %>
          </div>
          <button data-action="commentToggle#toggle">
            <%= commentbtn_display(comment) %>
          </button>
        </div>
        <div class="text-xs text-gray-400">
          <%= comment.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </div>
        <div data-editComment-target="text"
             class="mb-2">
          <%= comment.content %>
        </div>
      </div>
    </div>
    <div data-commentToggle-target="display"
         data-editComment-target="hide"
         style="display: none;"
         class="absolute right-3 top-6 z-10">
      <div class="commentinnerbg">
        <a href="#" 
           data-action="editComment#edit"
           class="commentbtnhover">
          <i class="fas fa-pencil-alt inline-block w-4"></i>編輯
        </a>
        <%= link_to comment_path(comment),
                    remote: true,
                    method: 'delete',
                    data: { id: comment.id },
                    class:"commentbtnhover" do %>
          <i class="fas fa-trash-alt inline-block w-4"></i>刪除
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/_comments.html.erb
<div>
  <% comments.each do |comment| %>
    <div class="relative">
      <div id="comment_<%= comment.id %>"
           data-controller="editComment commentToggle"
           data-editComment-id-value="<%= comment.id %>"
           class="px-3.5 border-b border-gray-300 mb-2">
        <div class="flex">
          <div class="flex justify-center items-start mr-1 mt-1">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar.url, size: '20x20', class: 'rounded-full' %>
            <% else %>
              <%= image_tag("104.png",:size => "20x20") %>
            <% end %>
          </div>
          <div>
            <div class="flex justify-between">
              <div class="text-xl">
                <%= comment.user.name %>
              </div>
              <button data-action="commentToggle#toggle">
                <%= commentbtn_display(comment) %>
              </button>
            </div>
            <div class="text-xs text-gray-400">
              <%= comment.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
            </div>
            <div data-editComment-target="text"
                class="mb-2">
              <%= comment.content %>
            </div>
          </div>
        </div>
        <div data-commentToggle-target="display"
             data-editComment-target="hide"
             style="display: none;"
             class="absolute right-3 top-6 z-10">
          <div class="commentinnerbg">
            <a href="#"
               data-action="editComment#edit"
               class="commentbtnhover">
              <i class="fas fa-pencil-alt inline-block w-4"></i>編輯
            </a>
            <%= link_to comment_path(comment),
                        remote: true,
                        method: 'delete',
                        data: { id: comment.id }, 
                        class:"commentbtnhover" do %>
              <i class="fas fa-trash-alt inline-block w-4"></i>刪除
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
</div>

app/views/notes/_side_bar.html.erb
<div class="sidebar h-screen" data-controller = "sideBar"
                     data-sideBar-target = "sidebar">

  <ul class="nav-list">
    <li class="my_space">
      <%= link_to notes_path do %>
        <i class="fas fa-user pr-2"></i>
        <span class="links_name text-xl">我的空間</span>
      <% end %>
    </li>
    <li>
      <div class="flex items-center">
        <i class="fas fa-search"></i>
        <div>
          <%= form_tag(notes_path, :method => "get") do %>
            <%= text_field_tag :search, nil, placeholder: "搜尋關鍵字或標籤", class: "w-40" %>
            <%= submit_tag "搜尋筆記" ,:note_name => nil, class: "hidden" %>
          <% end %>
        </div>
      </div>
    </li>
    <li class="create"
        style="width: 200px;">
      <%=link_to notes_path, method: 'post' do %>
        <i class="fas fa-plus"></i>
        <span class="links_name">建立筆記</span>
      <% end %>
    </li>
    <li>
      <%= link_to notes_path do %>
        <i class="fas fa-lock"></i>
        <span class="links_name">我的筆記</span>
      <% end %>
    </li>
  </ul>
  <ul class="nave-list list2 w-full">
    <li>
      <%= link_to users_collections_path do %>
        <i class="fas fa-bookmark"></i>
        <span class="links_name">收藏</span>
      <% end %>
    </li>
    <li class="user_info px-4">
      <div class="flex">
        <div class="flex justify-center items-center ml-1 mr-2">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.url, size: '20x20', class: 'rounded-full' %>
          <% else %>
            <%= image_tag("104.png",:size => "20x20") %>
          <% end %>
        </div>
        <div class="flex items-center w-20">
          <%= current_user.name %>
        </div>
      </div>
      <div>
        <div class="info-btns flex" data-controller="sideBar">
          <span data-action="click->sideBar#infoBoxToggle">
            <i class="fas fa-chevron-down"></i>
          </span>
          <span>
            <i class="fas fa-question"></i>
          </span>
          <div class="w-40 h-24 py-2 absolute rounded bg-gray-lightest_s bottom-full right-12"
               style="display: none;"
               data-sideBar-target="infoBox">
            <% if current_user %>
              <div>
                <%= link_to edit_registration_path(:user), class:'pl-4 py-1.5' do %>
                  <i class="fas fa-cog"
                     style="line-height: 14px; height: 14px; font-size: 14px;"> 設定</i>
                <% end %>
              </div>
              <div>
                <%= link_to user_private_note_private_path(current_user.id), class:'pl-3.5 py-1.5' do %>
                  <i class="fas fa-user-alt w-24"
                     style="line-height: 14px; height: 14px; font-size: 14px;"> 個人公開頁</i>
                <% end %>
              </div>
              <div>
                <%= link_to destroy_user_session_path, :method => :delete, class:'pl-4 py-1.5' do %>
                  <i class="fas fa-sign-out-alt"
                     style="line-height: 14px; height: 14px; font-size: 14px;"> 登出</i>
                <% end %>
              </div>
            <% else %>
              <div>
                <%= link_to '註冊', new_registration_path(:user), class:'pl-4 py-1' %>
              </div>
              <div>
                <%= link_to '登入', new_session_path(:user), class:'pl-4 py-1' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </ul>
  <div class="handle -right-0 w-6 z-10">
    <div class="handle-btn left-2">
    </div>
  </div>
</div>

app/views/notes/_side_nav.html.erb
<nav class="flex bg-gray-dark w-12 z-10 h-screen sticky top-0">
  <div class="side-nav-off">
  </div>
  <div class="side-nav-on w-60 z-20">
    <div class="side-bar-btn flex justify-center text-lg py-1.5">
      <%= link_to notes_path do %>
        <i class="fas fa-user pr-2"></i>我的空間
      <% end %>
    </div>
    <div class="flex">
      <i class="fa-solid fa-magnifying-glass z-10"></i>
      <%= form_tag(notes_path, :method => "get") do %>
        <%= text_field_tag :search, nil, placeholder: "搜尋關鍵字或標籤", class: "m-3 bg-gray-lightest p-1 rounded w-full" %>
        <%= submit_tag "搜尋筆記" ,:note_name => nil, class: "hidden" %>
      <% end %>
    </div >
    <div class="green-btn">
      <%=link_to notes_path, method: 'post' do %>
        <i class="fas fa-plus"></i>建立筆記
      <% end %>
    </div>
    <div class="side-bar-btn">
      <%= link_to notes_path do %>
        <i class="fas fa-lock"></i>我的筆記
      <% end %>
    </div>
    <div class="side-bar-btn">
      <%= link_to notes_path do %>
        <i class="fas fa-users"></i>協作筆記
      <% end %>
    </div>
    <div class="side-bar-btn">
      <%= link_to users_collections_path do %>
        <i class="fas fa-bookmark"></i>收藏
      <% end %>
    </div>
    <div class="inline-block mt-auto">
      <div class="text-sm mx-3 my-3 py-1 mt-auto">
        <%= link_to "個人公開頁", user_private_note_private_path(current_user)%>
      </div>
      <div class="block text-sm mx-3 mt-3 py-1">
        <% if current_user %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('個人帳戶設定', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/notes/edit.html.erb
<main class="show-main">
  <nav class="editor-nav justify-between">
    <div class="flex">
      <div class="logol">
        <%= link_to notes_path do %>
          <i class="fas fa-book-open text-xl"></i>RackMD
        <% end %>
      </div>
      <div class="switch-btns">
        <i class="fas fa-pencil-alt"></i>
        <i class="fas fa-columns"></i>
        <i class="far fa-eye"></i>
      </div>
    </div>
    
    <div data-controller="commentToggle"
         class="flex items-center relative">
        <i data-action="click->commentToggle#toggle"
           class="fas fa-share-alt text-lg text-gray-lightest_s hover:text-gray-rackmd cursor-pointer">
        </i>
        <div data-commentToggle-target="display"
             style="display: none;"
             class="bg-white w-56 p-4 shadow absolute top-full right-20 z-10">
          <div class="text-xs text-gray-light">
            公開發表
          </div>
          <button class="rounded py-2">
            <%= publicbtn_display(@note) %>
          </button>
          <div class="text-xs text-gray-light">
            當選擇公開發表，網路上的所有人皆可以尋找及瀏覽到這篇筆記。 <br>
            在<%= link_to "公開頁面", user_public_note_path(current_user.id), class:"text-blue-400 border-b border-blue-400"%>檢視所有已公開發表的筆記。
          </div>
        </div>
        <button class="flex items-center text-white bg-blue-500 hover:bg-blue-600 py-1 rounded">
          <i class="fas fa-users text-xs w-16"> 1 連線</i>
        </button>
    </div>
  </nav>
  <div class="editor">
    <div class="editor-write">
      <div class="toolbar">
        <div class="btn-toolbar" role="toolbar" aria-label="Editor toolbar">
          <div class="btn-group" role="group">
            <a id="makeBold" class="btn btn-ed title="Bold">
              <i class="fa fa-bold fa-fw"></i>
            </a>
            <a id="makeItalic" class="btn btn-ed title="Italic">
              <i class="fa fa-italic fa-fw"></i>
            </a>
            <a id="makeStrike" class="btn btn-ed title="Strikethrough">
              <i class="fa fa-strikethrough fa-fw"></i>
            </a>
            <a id="makeHeader" class="btn btn-ed title="Heading">
              <i class="fa fa-h1 fa-fw">H</i>
            </a>
            <a id="makeCode" class="btn btn-ed title="Code">
              <i class="fa fa-code fa-fw"></i>
            </a>
            <a id="makeQuote" class="btn btn-ed title="Quote">
              <i class="fa fa-quote-right fa-fw"></i>
            </a>
            <a id="makeGenericList" class="btn btn-ed title="List">
              <i class="fa fa-list fa-fw"></i>
            </a>
            <a id="makeOrderedList" class="btn btn-ed title="Numbered List">
              <i class="fa fa-list-ol fa-fw"></i>
            </a>
            <a id="makeCheckList" class="btn btn-ed title="Check List">
              <i class="fa fa-check-square fa-fw"></i>
            </a>
            <a id="makeLink" class="btn btn-ed title="Link">
              <i class="fa fa-link fa-fw"></i>
            </a>
            <a id="makeImage" class="btn btn-ed title="Image">
              <i class="fa fa-image fa-fw"></i>
            </a>
            <a id="makeTable" class="btn btn-ed title="Table">
              <i class="fa fa-table fa-fw"></i>
            </a>
            <a id="makeLine" class="btn btn-ed title="Line">
              <i class="fa fa-minus fa-fw"></i>
            </a>
            <a id="makeComment" class="btn btn-ed title="Comment">
              <i class="fa fa-comment fa-fw"></i>
            </a>
          </div>
          <span class="btn-group table-tools hidden-xs" style="display: none;">
            <span class="separator" style="margin-left: -10px;">|</span>
            <span>Row</span>
            <a id="insertRow" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Insert Row">
              <i class="fa fa-plus-circle fa-fw"></i>
            </a>
            <a id="deleteRow" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Delete Row">
              <i class="fa fa-minus-circle fa-fw"></i>
            </a>
            <a id="moveRowUp" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Move Row Up">
              <i class="fa fa-long-arrow-up fa-fw"></i>
            </a>
            <a id="moveRowDown" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Move Row Down">
              <i class="fa fa-long-arrow-down fa-fw"></i>
            </a>
            <span>Column</span>
            <a id="insertColumn" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Insert Column">
              <i class="fa fa-plus-circle fa-fw"></i>
            </a>
            <a id="deleteColumn" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Delete Column">
              <i class="fa fa-minus-circle fa-fw"></i>
            </a>
            <a id="moveColumnLeft" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Move Column Left">
              <i class="fa fa-long-arrow-left fa-fw"></i>
            </a>
            <a id="moveColumnRight" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Move Column Right">
              <i class="fa fa-long-arrow-right fa-fw"></i>
            </a>
            <span>Alignment</span>
            <a id="alignLeft" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Align Left">
              <i class="fa fa-align-left fa-fw"></i>
            </a>
            <a id="alignCenter" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Align Center">
              <i class="fa fa-align-center fa-fw"></i>
            </a>
            <a id="alignRight" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Align Right">
              <i class="fa fa-align-right fa-fw"></i>
            </a>
            <a id="alignNone" class="btn btn-sm btn-dark text-uppercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Align None">
              <i class="fa fa-ban fa-fw"></i>
            </a>
          </span>
        </div>
      </div>
      <div class="codemirror">
        <h1><------這邊要放codemirror!!!------></h1>
      </div>
    </div>
    <div class="editor-show">
      <div class="editor-show-bar">
        <div>
          <span>變更於小時之前</span>
        </div>
        <div class="icon-btns">
          <div data-controller="favorite"
              data-favorite-id-value="<%= @note.id %>">
            <a href="#"
              id = "favorite_btn"
              data-action="favorite#addFavorite"
              data-id="<%= @note.id %>">
              <%= favorite_icon(current_user, @note) %>
            </a>
            <span data-favorite-target='counter' >
              <%= @likes %>
            </span>
          </div>
          <div data-controller="collect"
              data-collect-id-value="<%= @note.id %>">
            <a data-action="collect#addCollection">
              <%= collection_icon(current_user, @note) %>
            </a>
          </div>
        </div>
      </div>
      <div class="editor-show-content">
        <h1><------這邊要放HTML!!!!!------></h1>
      </div>
    </div>
    <div data-controller="commentToggle"
              class="flex">
      <button class="w-8 h-8 border border-gray-300 mr-8 rounded mt-6 flex justify-center items-center"
              data-action="commentToggle#toggle">
        <i class="fas fa-comment-dots text-sm text-gray-lightest_s"></i>
      </button>
      <div data-commentToggle-target="display"
           style="display: none;"
           class="mr-4 my-6 border border-gray-300 rounded w-60 overflow-y-scroll">
        <div id="comments" class="mt-2">
          <%= render "comments", comments: @comments %>
        </div>
        <div class="">
          <%= render "createComment", note: @note, comment: @comment %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/notes/show.html.erb
<div class="h-screen">
  <nav class="editor-nav justify-between">
    <div class="flex">
      <div class="logol">
        <%= link_to notes_path do %>
          <i class="fas fa-book-open text-xl"></i>RackMD
        <% end %>
      </div>
      <div class="switch-btns">
        <i class="fas fa-pencil-alt"></i>
        <i class="fas fa-columns"></i>
        <i class="far fa-eye"></i>
      </div>
    </div>
  
    <div data-controller="commentToggle"
          class="flex items-center relative">
      <i data-action="click->commentToggle#toggle"
          class="fas fa-share-alt text-lg text-gray-lightest_s hover:text-gray-rackmd cursor-pointer">
      </i>
      <div data-commentToggle-target="display"
            style="display: none;"
            class="bg-white w-56 p-4 shadow absolute top-full right-20 z-20">
        <div class="text-xs text-gray-light">
          公開發表
        </div>
        <button class="rounded py-2">
          <%= publicbtn_display(@note) %>
        </button>
        <div class="text-xs text-gray-light">
          當選擇公開發表，網路上的所有人皆可以尋找及瀏覽到這篇筆記。 <br>
          在<%= link_to "公開頁面", user_public_note_path(current_user.id), class:"text-blue-400 border-b border-blue-400"%>檢視所有已公開發表的筆記。
        </div>
      </div>
      <div class="flex justify-center items-center px-2">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar.url, size: '30x30', class: 'rounded-full' %>
        <% else %>
          <%= image_tag("104.png",:size => "30x30") %>
        <% end %>
      </div>
      <button class="flex items-center text-white bg-blue-500 hover:bg-blue-600 py-1 rounded">
        <i class="fas fa-users text-xs w-16"> 1 連線</i>
      </button>
    </div>
  </nav>
  
  <div class="flex"
       data-controller="commentToggle">
    <div class="relative w-screen">
      <div id="editor" data-controller="autosave"
                       data-action="keyup->autosave#updateValue"
                       data-addTags-target="editor"
                       data-addTags-id-value="<%= @note.id %>"
                       data-autosave-id-value="<%= @note.id %>"
                       data-content="<%= @note.content %>"
                       class="w-full">
      </div>
      <div class="absolute right-0 top-12 z-10">
        <div class="flex items-center">
          <div class="icon-btns">
            <div data-controller="favorite"
                data-favorite-id-value="<%= @note.id %>">
              <a href="#"
                id = "favorite_btn"
                data-action="favorite#addFavorite"
                data-id="<%= @note.id %>">
                <%= favorite_icon(current_user, @note) %>
              </a>
              <span data-favorite-target='counter' >
                <%= @likes %>
              </span>
            </div>
          </div>
          <div data-controller="collect"
                data-collect-id-value="<%= @note.id %>"
                class="mx-3">
            <a data-action="collect#addCollection">
              <%= collection_icon(current_user, @note) %>
            </a>
          </div>
          <div>
            <button class="w-8 h-8 border border-gray-300 mr-8 rounded flex justify-center items-center"
                    data-action="commentToggle#toggle">
              <i class="fas fa-comment-dots text-sm text-gray-lightest_s bg-white"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  
  
    <div data-commentToggle-target="display"
            style="display: none;"
            class="mx-4 my-2 border border-gray-300 rounded w-60 overflow-y-scroll relative z-10 bg-white">
      <div id="comments" class="mt-2">
        <%= render "comments", comments: @comments %>
      </div>
      <div>
        <%= render "createComment", note: @note, comment: @comment %>
      </div>
    </div>
<div id="editor" data-controller="autosave"
                 data-action="keyup->autosave#updateValue"
                 data-autosave-target="editor"
                 data-autosave-id-value="<%= @note.id %>"
                 data-content="<%= @note.content %>"></div>
  </div>
</div>